#!/bin/bash

inc=1

for f in ./*
do
    if [[ $f == *Transparent* ]]; then
        #echo $f
        #mv $f $inc'.png'
        echo "mv $f icon_$inc.png"
        mv "$f" icon_$inc.png
        inc=$((inc+1))
    fi
done
